In [35]:
import torch
import torch.nn as nn


class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.x = nn.Parameter(torch.randn(5, 5), requires_grad = True)
        self.y = nn.Parameter(torch.randn(5, 5), requires_grad = True)
    
    def forward(self, z):
        return torch.matmul(z, self.x) * (torch.matmul(z, self.y) + 1)
    
model = Model()

In [36]:
model.x.requires_grad = False
model.x.requires_grad
opt = torch.optim.Adam(model.parameters(), lr = 1e-2)

In [42]:
x = torch.randn(10, 5)
y = torch.randn(10, 5)
lossf = torch.nn.MSELoss()

for i in range(10):
    opt.zero_grad()
    output = model(x)
    loss = lossf(y, output)
    loss.backward()
    print(model.y.grad)
    opt.step()
    print(f"\n\nEpoch {i}")


tensor([[-2.0113, -2.4264,  0.9452,  0.8486, -1.2989],
        [-2.6915, -0.4658,  0.7666,  3.8840,  1.9867],
        [-3.5865, -2.9451,  1.7541,  1.8197,  0.2162],
        [ 0.6963,  0.9923, -1.4843,  0.0925,  0.9868],
        [-0.3378,  0.3021, -0.0041,  1.2658, -1.5710]])


Epoch 0
tensor([[-1.9948e+00, -2.4198e+00,  9.4191e-01,  8.6038e-01, -1.2635e+00],
        [-2.6723e+00, -4.5738e-01,  7.6603e-01,  3.8518e+00,  1.9599e+00],
        [-3.5679e+00, -2.9322e+00,  1.7530e+00,  1.8041e+00,  2.1613e-01],
        [ 6.8619e-01,  9.9262e-01, -1.4803e+00,  6.2050e-02,  9.5319e-01],
        [-3.4668e-01,  2.8849e-01, -6.6173e-04,  1.3003e+00, -1.5263e+00]])


Epoch 1
tensor([[-1.9769e+00, -2.4095e+00,  9.3857e-01,  8.6979e-01, -1.2269e+00],
        [-2.6476e+00, -4.4993e-01,  7.6495e-01,  3.8194e+00,  1.9327e+00],
        [-3.5446e+00, -2.9172e+00,  1.7503e+00,  1.7878e+00,  2.1681e-01],
        [ 6.7661e-01,  9.9124e-01, -1.4761e+00,  3.3946e-02,  9.1860e-01],
        [-3.5551e-01,  2.763